### ISSUE TITLE
Use gDrive alongside Onedrive

### ISSUE THREAD

**Issue by Christian4561** [mkaminsky11/codeyourcloud#10]
Hello. I am a user of both Google Drive and Microsoft Onedrive. I recently found your website and found that I could use both. I signed in with my Google Account first. Then I tried to go back and sign in with my Microsoft account, but I can't without signing out of my Google Account entirely. Is there any was to quickly switch between the two? Thanks!

**Comment by mkaminsky11** [comment]
Great idea! I'll have it done in the next day or two,

**Comment by Christian4561** [comment]
Thanks!

**Comment by mkaminsky11** [comment]
All done!

![swap_issue](https://cloud.githubusercontent.com/assets/4978455/12392717/05ebb9f0-bdbf-11e5-9de7-e0708f245fd9.png)

**Comment by Christian4561** [comment]
Hello! I went and tried this feature out. I don't know if it's just my browser, but whenever I use the Switch To Onedrive button, it takes me to [https://codeyourcloud.com/="https://codeyourcloud.com?sky=true"], which gives me a 404 error. When I switch to Onedrive, the Switch To Google Drive button, it works. Again, not sure if this is just my browser.

**Comment by mkaminsky11** [comment]
sorry! looks I just made a small typo. It should be fixed now.
