### ISSUE TITLE
GitHub & DropBox Integration

### ISSUE THREAD

**Issue by tyrollins** [mkaminsky11/codeyourcloud#11]
Any plans to implement GitHub integration, allowing a user to work with gists? 
Or possibly Dropbox? 

Additionally, I noticed a mention of a JS repl, is this still a feature or has it been removed?

**Comment by mkaminsky11** [comment]
I had tried to implement Dropbox functionality, but I couldn't get it to work exactly like Google Drive or Onedrive. I may add a feature where files can be imported from Github or Dropbox in the future.

As for the JS Repl, that was removed, and I'm still working on re-writing it. Sorry for the confusion
