### ISSUE TITLE
Caracters not saving properly

### ISSUE THREAD

**Issue by RielN** [mkaminsky11/codeyourcloud#2]
Known issue, but we keep walking into this. The è character for instance for a customer project. Everytime we open the file, it gets saved wrong. Opened with another editor (carat) shows the wrong symbol

Regards!

![screenshot 2014-08-26 at 10 33 22](https://cloud.githubusercontent.com/assets/3995834/4041830/ac322e94-2cfb-11e4-9e24-11c8699ce333.png)

**Comment by Xandernardo** [comment]
I will try to add to this problem. The other day the program saved perfectly some chars like "Ó", "É" and such, but today it doesn't load the file properly, showing the same Error as the OP shown. 

Hope this helps

**Comment by mkaminsky11** [comment]
this might be a problem with how Google stores the characters in the file. I'll look into it a bit more

**Comment by mkaminsky11** [comment]
I've figured out a solution, it should be implemented in the next day or two

**Comment by Xandernardo** [comment]
Thanks for the fast response, your app is really useful for fast editing files directly in the cloud, which saved me a lot of time.

Good luck and thanks again for this awesome tool :)

**Comment by mkaminsky11** [comment]
I'm sorry to say that my "solution" won't work after all. For some reason, Google Drive is unable to save these characters properly, even when they are escaped to unicode codes (so é would become something like "\u00e9"). 

Escaping it also creates the problem of the edits being shifted because of the escaped characters.

I'll look into it some more, but for now, I'm going to have to close the issue, because it's not one which I am able to fix.

**Comment by mkaminsky11** [comment]
actually, I managed to fix the problem. it should work now. cheers!

**Comment by Xandernardo** [comment]
Sorry for the late answer, but I guess that saying thanks is the less I can do for all the good your tool did to me :). I grow tired of shady text editors for google, and having an open source one for it feels refreshing. It saved a lot of time for editing .sql files online, which oddly google doesn't let you edit with their own tools.

In any case, thank you for your great tool, I hope others can see in it what I see and use it too.

Have fun and good luck :)
