### ISSUE TITLE
Loading icon does not disapear

### ISSUE THREAD

**Issue by Conchylicultor** [mkaminsky11/codeyourcloud#3]
When I open a file directly from drive (right clic > open with). The file open, I can edit it but the loading icon never disapear. Here is a screenshot:

![infinite_loading](https://cloud.githubusercontent.com/assets/9047355/6036556/12060a5c-ac8a-11e4-8ec8-ed48f444821e.png)

Also, I cannot open ".pro" files (qt project files) directly from drive (right clic > open with), the association must be missing or something

Great app otherwise :)

**Comment by mkaminsky11** [comment]
thanks for the notice. Both of those should be fixed now.

**Comment by Conchylicultor** [comment]
Thank you, it's working.
Here are some other text files I cannot directly open from drive:
.yml (YAML),
.dart (and is it possible to add syntax highlighting for this one ? it is supported by codemirror)
.hpp (c++) !!!!
.cc (c++)
.frag and .vert (commly used Glsl extention)
.desktop
.pro.user
Basicaly all text file without extention (Makefile, Readme,...)

**Comment by mkaminsky11** [comment]
ok. sorry for the late reply. This is all fixed.

I also changed the permissions so that all files with the mimeType "text/plain" can be opened, so that should include any other file extensions.

**Comment by Conchylicultor** [comment]
Thank you
