### ISSUE TITLE
we redirect tu https://codeyourcloud.com/about/

### ISSUE THREAD

**Issue by bascunancorp** [mkaminsky11/codeyourcloud#5]
when we try open a file, we always redirected to https://codeyourcloud.com/about/

**Comment by mkaminsky11** [comment]
try going to https://codeyourcloud.com?no=true&force=true&output=true . Then, look in the javascript console and see what is says. Also are you using a custom domain (so, `foo@example.com` instead of `foo@gmail.com`)? This may be the issue.

**Comment by adamundercover** [comment]
I've been having the same problem (works in FF not Chrome). Here's the output:
![selection_010](https://cloud.githubusercontent.com/assets/4150080/8023176/3b67ec62-0d42-11e5-8ca2-ed3c5ccd24e2.png)

**Comment by mkaminsky11** [comment]
this means that there's some type of authentication error on Google's end...are you using a custom domain (see my previous comment) or multiple accounts? It's bizarre that this is only happening in Chrome.

**Comment by adamundercover** [comment]
Nope, just a standard @gmail.com

**Comment by adamundercover** [comment]
Mucking around with my browser right now, the cause seems to be that I'm blocking third-party cookies. I've now enabled third-party cookies from google.com and accounts.google.com, problem solved! I hope this helps someone (and sorry for wasting your time)

**Comment by mkaminsky11** [comment]
no problem! glad the issue was found.

**Comment by bascunancorp** [comment]
thank to both of you. 
now its working 
Regards
